#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE $POSTGRES_KEYCLOAK_DATABASE;
    \c $POSTGRES_KEYCLOAK_DATABASE
    CREATE USER $POSTGRES_KEYCLOAK_USER WITH PASSWORD '$POSTGRES_KEYCLOAK_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_KEYCLOAK_DATABASE TO $POSTGRES_KEYCLOAK_USER;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $POSTGRES_KEYCLOAK_USER;
EOSQL